services:
  db:
    image: mysql:8.0
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fiap
      MYSQL_USER: fiap
      MYSQL_PASSWORD: fiap

volumes:
  mysql_data: {}