version: '3.7'

services:

  fiap-self-service:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: 'host'
    restart: always
    depends_on:
      - db-mysql
    ports:
      - 3000:3000
    environment:
      DB_HOST: fiap
      DB_USER: fiap
      DB_PASSWORD: fiap

  db-mysql:
    image: mysql:8.0
    restart: always
    network_mode: 'host'
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fiap
      MYSQL_USER: fiap
      MYSQL_PASSWORD: fiap

volumes:
  mysql_data: {}

networks:
  fiap-net:
    driver: bridge