apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fiap-pvc-mysql
  labels:
    name: fiap-pvc-mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi 
  storageClassName: local-storage-db