apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  labels:
    name: api-config
data:
  DATABASE_HOST: "database-1.cscwzdenepah.us-east-1.rds.amazonaws.com" # SUBSTITUI PELO CLUSTER IP mysql-nodeport-svc
  DATABASE_PORT: "3306"
  APPLICATION_PORT: "3000"
