apiVersion: v1
kind: Service
metadata:
  name: fiap-api-service
spec:
  type: LoadBalancer
  selector:
    app: fiap-api
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30000