apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  labels:
    name: api-config
data:
  DATABASE_HOST: "localhost" # SUBSTITUI PELO CLUSTER IP mysql-nodeport-svc
  DATABASE_PORT: "3306"
  APPLICATION_PORT: "3000"
