apiVersion: v1
kind: Secret
metadata:
  name: api-secret
type: Opaque
data:
  DATABASE_USERNAME: cm9vdA==
  DATABASE_PASSWORD: ZmlhcHJvb3Q=
  DATABASE_DATABASE: ZmlhcFNlbGZTZXJ2aWNlRGI=
  DOCUMENT_DATABASE_USERNAME: ZmlhcA==
  DOCUMENT_DATABASE_PASSWORD: ZmlhcA==
  DOCUMENT_DATABASE_DATABASE: ZmlhcA==
