name: CD
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to DockerHub
        run: docker login -u jacksoncarbonera -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t jacksoncarbonera/fiap-self-service .
          docker push jacksoncarbonera/fiap-self-service

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Update kube config
        run: aws eks update-kubeconfig --name fiap-k8s-cluster --region us-east-1

      - name: Deploy to EKS
        run: |
          kubectl apply -f kubernetes/metrics  
          kubectl apply -f kubernetes/api 

      - name: Verificar Status do Deploy
        run: kubectl get pods